name: CD
on:
  workflow_dispatch:
    inputs:
      ambiente:
        type: choice
        options: [DEV, HOM, PRD]
        default: DEV

jobs:
  esteira:
    uses: GDD-Core/esteiras-workflows/.github/workflows/cd-bff-node.yml@main
    with:
      ambiente: ${{ inputs.ambiente }}
